keys:
  - &ckgxrg age1yy9f2spvzv6fuv9c3x0nln3z7r03922eafenrx7nud9qdkvh042qr0zd76

  - &welkin age1a3s6p6ltn9j9yj4dnllmgnf59lvxf59fwy7s34z4zw06um2jhfgs9ulxqv
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *ckgxrg
      - *welkin
