everpivot:
    shiori:
        env: ENC[AES256_GCM,data:FYHIh6FLKaQ6/haPQ050NQtzuEMrj31ZN4f+kD3uk+Vf8ufvpFERz1q7Gw==,iv:382NzHqjEOSGdmDEGSzG3n8TbtbvnGsiJftYz8SQnOE=,tag:FVtgg9L8OdmWjPnKaCBFOg==,type:str]
archiva:
    gitea:
        dbpasswd: ENC[AES256_GCM,data:jdilPbi/SBWJ13TkWYs7eGoVNMe6n+pKHw==,iv:E5DRF720Ehha2/BUzh2TOUUqu/RL2BWZkXY2EJE5ui4=,tag:RPENH8GMxsnRf6GWtFa5Dg==,type:str]
stargazer:
    synapse:
        registration_secret.conf: ENC[AES256_GCM,data:p5kVL5W11w7LVSys0BYnbOPweYQrRSTsutGos64J9atVftlHcqN/XHGVtIe/TpF7F6mQ2Xw8l5eSZITA+/oQaSyMpJ3wUxPdgmTlTHbwW5UNlsa/LAwnDr11RGs=,iv:c3rKswso6ny4ijqb0RupZf+xvi2+s0qklAqoVOMEym0=,tag:qzMPCg77OjKhp8ZjAIijzQ==,type:str]
paralace:
    davis:
        admin-passwd: ENC[AES256_GCM,data:yq9kGeUJc94ZUXHsSrW+ag==,iv:x9pvzHSWnHqeFLG6D239eHIpuiOxhjAL49aYSObov1k=,tag:o/MGQHHL/b37CeLrWxi3Lw==,type:str]
        app-secret: ENC[AES256_GCM,data:R4n51cBY7rzdYq7wqaD/br3Oq69sROHwvAf1d1nd+sCSevr9MduPS3RD4bZcUer+,iv:hi1EddC6BUVXsCG9VPFECiAj3qPYs/g31dbjiKBibVI=,tag:tmvo4S6O6FX+KMBLm3qS/A==,type:str]
    firefly-iii:
        app-key: ENC[AES256_GCM,data:jOkajU9U4QClU0kDwRmC3OB4iHibjkeGju4iI0/9bzYFDOqwGfnVZmtJjqEr9TmRIka9,iv:Ir1sXga46wb42GNCe+vC2npK9rNWzoFOwH1GbAbvKOo=,tag:atlM4A6B99Oi5OjHzLUjZQ==,type:str]
    freshrss:
        passwd: ENC[AES256_GCM,data:zyr8/kohGawAFjL8mcmGUA==,iv:WjLUej+RanuyZmctkZkZMYJlHEXslT1rSjRxXhg82Rk=,tag:COxAbCnxXRCc4Wa6CEIPUA==,type:str]
sops:
    age:
        - recipient: age1yy9f2spvzv6fuv9c3x0nln3z7r03922eafenrx7nud9qdkvh042qr0zd76
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6T010ckpIZDBYd21IVkR4
            eHYyVWt6UFgvV3ppcXowMFFwRGNZRGxQc2h3CnlHZUVMUnFDUzZwaFVhVVNMMTNs
            cmpQTStGcndBWGRtcEZkMWszYzlPZk0KLS0tIDJYZS9LV2RXNm9PR0VHWGpkTW82
            cVNtaHZLTllLdEhTV0x3dzVpR2FpRFkK1K1x8iXPC80GBKKL+IADrbp5uzI6FfVU
            O/xkWdaz+91OgEh89ALETahERsWDdqZRWvmnpVPcrsnneB5EvOFigg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uqmm69mv5g5nae9rgaf62wdxva8v37fnydu3cjm743xpdh9cgdvs0z4j82
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRFYzVGlSMjUzaEVZcUdv
            cW1GM2JSSU9jTjNoUFQvMXFDL2dHQ2xJZkRvCjVtZ1lqVDlSWCtXankyOWJmdk1w
            Y0ppWXJrU3cxMkdMRTVrYmljTEhEWjAKLS0tIFlXcnBKQXJvK1AwRklxTVJWWDBt
            ZTJFUDlRbFlnSHNGN3gxM200SnUxcGcKd91Fw9ztrzEHBbKPou7odOMkUAiY27cY
            x8o9vj0ai0IynMQO8Kju4a7w38+hYiUlDmTtVJ29oahJgkjTtGOnig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-03T08:08:32Z"
    mac: ENC[AES256_GCM,data:Ak4ccSw5rssXokycDZ6AWKyKhPzX5AYoWCjTe1xFs2xTV8iOPdJP0kQXeN9E1CXsmAM3UuXZeOX6/RcpRx9zUznq/JvXWv+Va3WhZvC5+6W6K+uYfGULbGTSqA5yvbuKye52fFy1YLpCuALO2hTX94S8GFcPDolK2TOjglfclak=,iv:zBUPcexcyDfTivTe0JJ1f98XLri8s/MtqqrArpkD3UA=,tag:HPxmI4Q1vFHphHpvGUYL3w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
